import type { PageServerLoad, Actions } from "./$types";
import { superValidate, fail, withFiles } from "sveltekit-superforms";
import { rateFormSchema } from "./schema";
import { zod } from "sveltekit-superforms/adapters";
import { ACCOUNT_ID, API_KEY } from "$env/static/private";

export const load: PageServerLoad = async () => {
    return {
        rateForm: await superValidate(zod(rateFormSchema)),
    };
};

export const actions: Actions = {
    default: async (event) => {
        const rateForm = await superValidate(event, zod(rateFormSchema));
        if (!rateForm.valid) {
            return fail(400, {
                rateForm,
            });
        };

        const imageBlob = await rateForm.data.image.arrayBuffer();
        async function run(model: string, input: any) {
            const response = await fetch(
                `https://api.cloudflare.com/client/v4/accounts/${ACCOUNT_ID}/ai/run/${model}`,
                {
                    headers: { Authorization: `Bearer ${API_KEY}`, "Content-Type": "application/json" },
                    method: "POST",
                    body: JSON.stringify(input),
                },
            );
            const result = await response.json();
            return result;
        };
        const imageInput = {
            image: [...new Uint8Array(imageBlob)],
            prompt: "Generate a description of the person in the image. Make it very detailed, mention every single little detail, including but not limited to the person's facial features, and the person's looks and general style, accessories, and every single little facial feature in detail like face shape, eye color, hair style, hair color, build, and clothing item the person has. If there is no person in the image, say error",
            max_tokens: 512,
        };
        const imageDescriptionResponse = await run("@cf/llava-hf/llava-1.5-7b-hf", imageInput);
        const imageDescription = imageDescriptionResponse.result.description;
        console.log("Image description: " + imageDescription);
        const ratingInput = {
            messages: [
                {
                    role: "user",
                    content: "You are an aura rater. Aura is the the distinctive atmosphere or quality that seems to surround and be generated by a person, aura is not just looks or facial features, it is just the overall presence of the person, a strong aura could have characteristics such as perfect hairline, perfect beard, perfect moustache or a perfect clean shave, as well as a well built body. A person with a strong aura could be Cristiano Ronaldo the football player, and a weak aura could be a homeless person or a fat person. You will be given an image description and based on that image description, rate the aura using a percentage on a scale of 0-100, 100 being the most aura/strong aura and 0 being a weak aura/lowest aura, to the closest two decimal points. Be harsh, don't be afraid to roast aspects of the person that are bad, so give them a low rating if they can improve on something, and give them a very high rating if they have good aura. Only return the percentage followed by your reasoning for the aura rating, and reason for why they got a high or a low aura score and how they can improve. Just remember, aura is not all looks, rather it is the presence exuded by the person. Also, don't use any formatting in the response. This is an example response: '69.42% This is my reasoning.' This is the image description: " + imageDescription,
                },
            ],
        };
        const ratingResponse = await run("@cf/meta/llama-3.2-3b-instruct", ratingInput);
        const ratingString = ratingResponse.result.response;
        const ratingNum = ratingString.match(/\d+\.\d{2}/);
        const ratingReasoning = ratingString.split('%')[1].trim();
        console.log("Rating: " + ratingNum);
        console.log("Reasoning: " + ratingReasoning);

        return withFiles({
            rateForm,
            rating: ratingNum,
            ratingReasoning: ratingReasoning,
        });
    },
};
